import{a as E,S as P,i as n}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const R="https://pixabay.com/api/",B=15,M="53055755-295da906459d55ec9ae018533";async function p(o,t=1){const s={key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:t};return(await E.get(R,{params:s})).data}const h=document.querySelector(".gallery"),g=document.querySelector(".loader"),m=document.querySelector(".load-more"),y=new P(".gallery a",{captionsData:"alt",captionDelay:250});function b(o){if(!Array.isArray(o)||o.length===0)return;const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:l,comments:q,downloads:$})=>`
      <li class="gallery-item">
        <a href="${i}">
          <img src="${s}" alt="${e}" loading="lazy" />
        </a>
        <div class="info">
          <p><b>Likes:</b> ${r}</p>
          <p><b>Views:</b> ${l}</p>
          <p><b>Comments:</b> ${q}</p>
          <p><b>Downloads:</b> ${$}</p>
        </div>
      </li>`).join("");h.insertAdjacentHTML("beforeend",t),y.refresh()}function H(){h.innerHTML="",y.refresh()}function L(){g.classList.remove("is-hidden")}function w(){g.classList.add("is-hidden")}function S(){m.classList.remove("is-hidden")}function d(){m.classList.add("is-hidden")}const f=document.getElementById("search-form"),O=f.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let u="",a=1,c=0;const v=15;f.addEventListener("submit",async o=>{o.preventDefault();const t=O.value.trim();if(!t){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}t!==u&&(u=t,a=1,c=0,H(),d());try{L();const s=await p(u,a),{hits:i,totalHits:e}=s;if(c=e,!i||i.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),d();return}b(i),a===1&&n.success({title:"Success",message:`Hooray! We found ${c} images.`,position:"topRight"}),a*v<c?S():(d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(s){console.error(s),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),f.reset()}});x.addEventListener("click",async()=>{if(u){a+=1;try{L();const o=await p(u,a),{hits:t}=o;if(!t||t.length===0){d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"});return}b(t);const s=document.querySelector(".gallery .gallery-item");if(s){const{height:e}=s.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}a*v>=c?(d(),n.info({title:"End of results",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch(o){console.error(o),n.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{w()}}});
//# sourceMappingURL=index.js.map
